# Generated by Django 3.1.1 on 2020-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('intro', models.TextField()),
                ('text', models.TextField()),
                ('img', models.CharField(default='', max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
